###### AWS CLOUD FORMATION - ANDRESSA LIMA ######
# Descrição: Instalar servidor Apache automaticamente na EC2

Description: Instalar Servidor Apache

Resources:
  MinhaInstancia:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0ed9277fb7eb570c9
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Webserver
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          yum update -y
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          echo "<h1>OLÁ AWS FOUNDATIONS da Andressa Lima!</h1>" > /var/www/html/index.html
